version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    hostname: minecraft
    ports:
      - "25565:25565"
    volumes:
        #  - "./Ponyhof:/data"
        - "./fohynop:/data"
    environment:
      EULA: "TRUE"
      CONSOLE: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
    restart: always
    links:
        - rcon
    networks:
        minecraft:
            ipv4_address: 10.10.11.11

  rcon:
      #  image: itzg/rcon
    build: ./rcon
    image: rcon:self
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"
    networks:
        minecraft:
            ipv4_address: 10.10.11.10
 
volumes:
  rcon:

networks:
    minecraft:
        ipam:
            driver: default
            config:
                - subnet: 10.10.11.0/24
